# Scrape the table

In [8]:
import requests
import re
from datetime import date
import pandas as pd

In [9]:
base_id = "appdbVBj7AnaiBL00"
table_name = "Berkeley%202021%20Scholarships "
url = "https://api.airtable.com/v0/" + base_id + "/" + table_name

api_key = "keyqosr8hSKDywgVJ"
headers = {"Authorization": "Bearer " + api_key}
params = ()

response = requests.get(url, params=params, headers=headers)
airtable_response = response.json()

airtable_records = airtable_response['records']

airtable_records

[{'id': 'rec2oGZucCcrQ1bzg',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 90000,
   'Attributes': ['C&F',
    'Non-traditional',
    'First-Gen Professional',
    'Low SES Background'],
   'GPA': '>3.5',
   'URM?': ['Black'],
   'Notes, Special Circumstance': 'Aid + Tech Scholarship, stats are as of 2020, but deferred to 2021',
   'LSAT': '164',
   'Full Time Work Experience': '6 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recDQZBaOvu7ESfd1',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 52500,
   'Attributes': ['LGBTQ+',
    'PI-oriented',
    'Non-traditional',
    'Low SES Background'],
   'GPA': '3.75-3.8',
   'LSAT': '170',
   'Full Time Work Experience': '8 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recGDfFiDA7I7j3fo',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 60000,
   'Attributes': ['LGBTQ+', 'PI-oriented'],
   'GPA': '3.8-3.85',
   'Update?': True,
   'URM?': ['Other URM not listed'],
   'Notes, Special Circumstance': 'I accidentally submitted a $60 entry. ',
   'LSAT': '164',
   'Full Time Work Experience': '2 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recL8CFNrxhnaSVD0',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 0,
   'Attributes': ['LGBTQ+', 'PI-oriented'],
   'GPA': '3.6-3.65',
   'Final Scholarship Offer': 60000,
   'Notes, Special Circumstance': '2019-20 cycle deferral. Info is based on aid negotiated in that cycle.',
   'LSAT': '168',
   'Full Time Work Experience': '>10 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recPqGjlvDcb7IoUI',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 60000,
   'Attributes': ['Non-traditional', 'Low SES Background'],
   'GPA': '3.75-3.8',
   'URM?': ['Other Hispanic/Latinx'],
   'Notes, Special Circumstance': 'Will be negotiating later on... Fingers crossed! ',
   'LSAT': '179',
   'Full Time Work Experience': '8 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recQGl527CYavxDlC',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 67500,
   'Attributes': ['College/Professional Athlete', 'PI-oriented'],
   'GPA': '3.75-3.8',
   'LSAT': '175',
   'Full Time Work Experience': '3 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recdR3mZAEtwnJCSB',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 90000,
   'Attributes': ['Foster/Adopted', 'LGBTQ+', 'PI-oriented', 'Disability'],
   'GPA': '3.9-3.95',
   'LSAT': '177',
   'Full Time Work Experience': '3 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recfEkr2jtqPz5eyJ',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 60,
   'Attributes': ['LGBTQ+', 'PI-oriented'],
   'GPA': '3.8-3.85',
   'URM?': ['Other URM not listed'],
   'LSAT': '164',
   'Full Time Work Experience': '2 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recjKwN4fCb4qEIEG',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 60000,
   'Attributes': ['PI-oriented',
    'First-Gen College',
    'First-Gen Professional'],
   'GPA': '3.95-4.0',
   'LSAT': '169',
   'Full Time Work Experience': '5 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recm80G1HUTfrrXae',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 75000},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recpCg0gxw5Mq19AD',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 90000,
   'Attributes': ['C&F',
    'Non-traditional',
    'PI-oriented',
    'Low SES Background',
    'LGBTQ+'],
   'GPA': '3.75-3.8',
   'URM?': ['Black', 'Native American', 'Puerto Rican'],
   'Notes, Special Circumstance': 'I am a special lady and Berkeley should love me',
   'LSAT': '171',
   'Full Time Work Experience': '3 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recpVgatPozO7RzcW',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 45000,
   'Attributes': ['LGBTQ+',
    'First-Gen College',
    'First-Gen Professional',
    'Low SES Background'],
   'GPA': '3.9-3.95',
   'URM?': ['Mexican'],
   'LSAT': '167',
   'Full Time Work Experience': '3 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recu4hClVU3CWQ8oE',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 52500,
   'Attributes': ['Disability', 'Non-traditional', 'PI-oriented'],
   'GPA': '3.75-3.8',
   'LSAT': '170',
   'Full Time Work Experience': '8 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recwYfxVxQeuMuTEM',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 75000,
   'Attributes': ['LGBTQ+', 'PI-oriented'],
   'GPA': '3.9-3.95',
   'URM?': ['Black'],
   'LSAT': '164',
   'Full Time Work Experience': '2 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recy4PGxRGIqIVJx6',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 120000,
   'Attributes': ['First-Gen College', 'First-Gen Professional'],
   'GPA': '3.8-3.85',
   'URM?': ['Mexican'],
   'LSAT': '168',
   'Full Time Work Experience': 'None'},
  'createdTime': '2021-03-03T00:31:23.000Z'},
 {'id': 'recyCR4RjbchQD9Nz',
  'fields': {'Initial Scholarship Offer (Total over 3 years)': 75000,
   'Attributes': ['LGBTQ+', 'Published Author', 'Low SES Background'],
   'GPA': '3.7-3.75',
   'LSAT': '166',
   'Full Time Work Experience': '2 years'},
  'createdTime': '2021-03-03T00:31:23.000Z'}]

In [22]:
df_list = []

for record in airtable_records:
    if ("LSAT" not in record['fields'] or 
       "GPA" not in record['fields'] or 
       ('Initial Scholarship Offer (Total over 3 years)' not in record['fields'] and 
        'Final Scholarship Offer' not in record['fields'])):
        continue
    
    df_list.append(pd.DataFrame({
        "Admission Date": [date.today()],
        "LSAT": [int(record['fields']['LSAT'])],
        "GPA": [float(re.search('\d\.\d+', record['fields']['GPA']).group()) 
                if re.search('\d\.\d+', record['fields']['GPA'])
                else 0],
        "URM?": ["Yes" if "URM?" in record['fields'] else "No"],
        "Date Scholarship Received": [date.today()],
        "Scholarship": [record['fields']['Final Scholarship Offer'] 
                        if 'Final Scholarship Offer' in record['fields']
                        else record['fields']['Initial Scholarship Offer (Total over 3 years)']],
        "Named Scholarship?": ["No"],
        "Conditional Scholarship?": ["No"]
    }))
    
df = pd.concat(df_list)

df

,Admission Date,LSAT,GPA,URM?,Date Scholarship Received,Scholarship,Named Scholarship?,Conditional Scholarship?
0,2021-03-02,164,3.50,Yes,2021-03-02,90000,No,No
0,2021-03-02,170,3.75,No,2021-03-02,52500,No,No
0,2021-03-02,164,3.80,Yes,2021-03-02,60000,No,No
0,2021-03-02,168,3.60,No,2021-03-02,60000,No,No
0,2021-03-02,179,3.75,Yes,2021-03-02,60000,No,No
0,2021-03-02,175,3.75,No,2021-03-02,67500,No,No
0,2021-03-02,177,3.90,No,2021-03-02,90000,No,No
0,2021-03-02,164,3.80,Yes,2021-03-02,60,No,No
0,2021-03-02,169,3.95,No,2021-03-02,60000,No,No
0,2021-03-02,171,3.75,Yes,2021-03-02,90000,No,No
0,2021-03-02,167,3.90,Yes,2021-03-02,45000,No,No
0,2021-03-02,170,3.75,No,2021-03-02,52500,No,No
0,2021-03-02,164,3.90,Yes,2021-03-02,75000,No,No
0,2021-03-02,168,3.80,Yes,2021-03-02,120000,No,No
0,2021-03-02,166,3.70,No,2021-03-02,75000,No,No